// Auto-generated barrel file for photography configs
// DO NOT EDIT - This file is regenerated by the config generator script

import brandMoment1Config from './brandMoment1';
import brandMoment10Config from './brandMoment10';
import brandMoment11Config from './brandMoment11';
import brandMoment12Config from './brandMoment12';
import brandMoment13Config from './brandMoment13';
import brandMoment2Config from './brandMoment2';
import brandMoment3Config from './brandMoment3';
import brandMoment4Config from './brandMoment4';
import brandMoment5Config from './brandMoment5';
import brandMoment6Config from './brandMoment6';
import brandMoment7Config from './brandMoment7';
import brandMoment8Config from './brandMoment8';
import brandMoment9Config from './brandMoment9';
import cardRender1Config from './cardRender1';
import cardRender2Config from './cardRender2';
import cardRender3Config from './cardRender3';
import debt1Config from './debt1';
import debt2Config from './debt2';
import debt3Config from './debt3';
import gaming1Config from './gaming1';
import gaming2Config from './gaming2';
import gaming3Config from './gaming3';
import general1Config from './general1';
import general10Config from './general10';
import general11Config from './general11';
import general12Config from './general12';
import general13Config from './general13';
import general14Config from './general14';
import general15Config from './general15';
import general16Config from './general16';
import general17Config from './general17';
import general18Config from './general18';
import general19Config from './general19';
import general2Config from './general2';
import general20Config from './general20';
import general21Config from './general21';
import general22Config from './general22';
import general23Config from './general23';
import general24Config from './general24';
import general25Config from './general25';
import general26Config from './general26';
import general27Config from './general27';
import general28Config from './general28';
import general3Config from './general3';
import general4Config from './general4';
import general5Config from './general5';
import general6Config from './general6';
import general7Config from './general7';
import general8Config from './general8';
import general9Config from './general9';
import negative1Config from './negative1';
import negative2Config from './negative2';
import negative3Config from './negative3';
import negative4Config from './negative4';
import negative5Config from './negative5';
import negative6Config from './negative6';
import negative7Config from './negative7';
import negative8Config from './negative8';
import placeholderConfig from './placeholder';
import positive1Config from './positive1';
import positive10Config from './positive10';
import positive11Config from './positive11';
import positive12Config from './positive12';
import positive13Config from './positive13';
import positive2Config from './positive2';
import positive3Config from './positive3';
import positive3LandscapeLargeConfig from './positive3LandscapeLarge';
import positive4Config from './positive4';
import positive5Config from './positive5';
import positive6Config from './positive6';
import positive7Config from './positive7';
import positive8Config from './positive8';
import positive9Config from './positive9';
import subscription1Config from './subscription1';
import subscription2Config from './subscription2';
import subscription3Config from './subscription3';
import womanonphonePumpkin4Config from './womanonphonePumpkin4';

export const configs = {
  brandMoment1: brandMoment1Config,
  brandMoment10: brandMoment10Config,
  brandMoment11: brandMoment11Config,
  brandMoment12: brandMoment12Config,
  brandMoment13: brandMoment13Config,
  brandMoment2: brandMoment2Config,
  brandMoment3: brandMoment3Config,
  brandMoment4: brandMoment4Config,
  brandMoment5: brandMoment5Config,
  brandMoment6: brandMoment6Config,
  brandMoment7: brandMoment7Config,
  brandMoment8: brandMoment8Config,
  brandMoment9: brandMoment9Config,
  cardRender1: cardRender1Config,
  cardRender2: cardRender2Config,
  cardRender3: cardRender3Config,
  debt1: debt1Config,
  debt2: debt2Config,
  debt3: debt3Config,
  gaming1: gaming1Config,
  gaming2: gaming2Config,
  gaming3: gaming3Config,
  general1: general1Config,
  general10: general10Config,
  general11: general11Config,
  general12: general12Config,
  general13: general13Config,
  general14: general14Config,
  general15: general15Config,
  general16: general16Config,
  general17: general17Config,
  general18: general18Config,
  general19: general19Config,
  general2: general2Config,
  general20: general20Config,
  general21: general21Config,
  general22: general22Config,
  general23: general23Config,
  general24: general24Config,
  general25: general25Config,
  general26: general26Config,
  general27: general27Config,
  general28: general28Config,
  general3: general3Config,
  general4: general4Config,
  general5: general5Config,
  general6: general6Config,
  general7: general7Config,
  general8: general8Config,
  general9: general9Config,
  negative1: negative1Config,
  negative2: negative2Config,
  negative3: negative3Config,
  negative4: negative4Config,
  negative5: negative5Config,
  negative6: negative6Config,
  negative7: negative7Config,
  negative8: negative8Config,
  placeholder: placeholderConfig,
  positive1: positive1Config,
  positive10: positive10Config,
  positive11: positive11Config,
  positive12: positive12Config,
  positive13: positive13Config,
  positive2: positive2Config,
  positive3: positive3Config,
  positive3LandscapeLarge: positive3LandscapeLargeConfig,
  positive4: positive4Config,
  positive5: positive5Config,
  positive6: positive6Config,
  positive7: positive7Config,
  positive8: positive8Config,
  positive9: positive9Config,
  subscription1: subscription1Config,
  subscription2: subscription2Config,
  subscription3: subscription3Config,
  womanonphonePumpkin4: womanonphonePumpkin4Config,
};

export type ConfigKeys = keyof typeof configs;

export default configs;
