/* eslint-disable custom/no-placeholder-photography */
/**
 * Auto-generated photography type definitions and assets
 * DO NOT EDIT MANUALLY - This file is regenerated by the image generation script
 */

import { CropType } from './types';

export enum PhotographyName {
  BRANDMOMENT1 = 'brandMoment1',
  BRANDMOMENT10 = 'brandMoment10',
  BRANDMOMENT11 = 'brandMoment11',
  BRANDMOMENT12 = 'brandMoment12',
  BRANDMOMENT13 = 'brandMoment13',
  BRANDMOMENT2 = 'brandMoment2',
  BRANDMOMENT3 = 'brandMoment3',
  BRANDMOMENT4 = 'brandMoment4',
  BRANDMOMENT5 = 'brandMoment5',
  BRANDMOMENT6 = 'brandMoment6',
  BRANDMOMENT7 = 'brandMoment7',
  BRANDMOMENT8 = 'brandMoment8',
  BRANDMOMENT9 = 'brandMoment9',
  CARDRENDER1 = 'cardRender1',
  CARDRENDER2 = 'cardRender2',
  CARDRENDER3 = 'cardRender3',
  GAMING1 = 'gaming1',
  GENERAL1 = 'general1',
  GENERAL10 = 'general10',
  GENERAL11 = 'general11',
  GENERAL12 = 'general12',
  GENERAL13 = 'general13',
  GENERAL14 = 'general14',
  GENERAL15 = 'general15',
  GENERAL16 = 'general16',
  GENERAL17 = 'general17',
  GENERAL18 = 'general18',
  GENERAL19 = 'general19',
  GENERAL2 = 'general2',
  GENERAL20 = 'general20',
  GENERAL21 = 'general21',
  GENERAL22 = 'general22',
  GENERAL23 = 'general23',
  GENERAL24 = 'general24',
  GENERAL25 = 'general25',
  GENERAL26 = 'general26',
  GENERAL27 = 'general27',
  GENERAL3 = 'general3',
  GENERAL4 = 'general4',
  GENERAL5 = 'general5',
  GENERAL6 = 'general6',
  GENERAL7 = 'general7',
  GENERAL8 = 'general8',
  GENERAL9 = 'general9',
  NEGATIVE1 = 'negative1',
  NEGATIVE2 = 'negative2',
  NEGATIVE3 = 'negative3',
  NEGATIVE4 = 'negative4',
  NEGATIVE5 = 'negative5',
  NEGATIVE6 = 'negative6',
  NEGATIVE7 = 'negative7',
  NEGATIVE8 = 'negative8',
  PLACEHOLDER = 'placeholder',
  POSITIVE1 = 'positive1',
  POSITIVE10 = 'positive10',
  POSITIVE11 = 'positive11',
  POSITIVE12 = 'positive12',
  POSITIVE13 = 'positive13',
  POSITIVE2 = 'positive2',
  POSITIVE3 = 'positive3',
  POSITIVE4 = 'positive4',
  POSITIVE5 = 'positive5',
  POSITIVE6 = 'positive6',
  POSITIVE7 = 'positive7',
  POSITIVE8 = 'positive8',
  POSITIVE9 = 'positive9',
}



/**
 * Type for the photography map
 */
export type PhotographyMap = Record<PhotographyName, {
  values: Partial<Record<CropType, any>>;
  appVersion: string;
  isBackendDependant: boolean;
}>

/**
 * Helper type to represent photography props
 */
export type BasePhotographyProps = {
  name: PhotographyName;
  cropType: CropType;
};

export const photoCropAvailability = {
  [CropType.PORTRAIT_LARGE]: [
    PhotographyName.BRANDMOMENT1,
    PhotographyName.BRANDMOMENT10,
    PhotographyName.BRANDMOMENT11,
    PhotographyName.BRANDMOMENT12,
    PhotographyName.BRANDMOMENT13,
    PhotographyName.BRANDMOMENT2,
    PhotographyName.BRANDMOMENT3,
    PhotographyName.BRANDMOMENT4,
    PhotographyName.BRANDMOMENT5,
    PhotographyName.BRANDMOMENT6,
    PhotographyName.BRANDMOMENT7,
    PhotographyName.BRANDMOMENT8,
    PhotographyName.BRANDMOMENT9,
    PhotographyName.CARDRENDER1,
    PhotographyName.CARDRENDER2,
    PhotographyName.CARDRENDER3,
    PhotographyName.GAMING1,
    PhotographyName.GENERAL1,
    PhotographyName.GENERAL10,
    PhotographyName.GENERAL11,
    PhotographyName.GENERAL12,
    PhotographyName.GENERAL13,
    PhotographyName.GENERAL14,
    PhotographyName.GENERAL15,
    PhotographyName.GENERAL16,
    PhotographyName.GENERAL17,
    PhotographyName.GENERAL18,
    PhotographyName.GENERAL19,
    PhotographyName.GENERAL2,
    PhotographyName.GENERAL20,
    PhotographyName.GENERAL21,
    PhotographyName.GENERAL22,
    PhotographyName.GENERAL23,
    PhotographyName.GENERAL24,
    PhotographyName.GENERAL25,
    PhotographyName.GENERAL26,
    PhotographyName.GENERAL27,
    PhotographyName.GENERAL3,
    PhotographyName.GENERAL4,
    PhotographyName.GENERAL5,
    PhotographyName.GENERAL6,
    PhotographyName.GENERAL7,
    PhotographyName.GENERAL8,
    PhotographyName.GENERAL9,
    PhotographyName.NEGATIVE1,
    PhotographyName.NEGATIVE2,
    PhotographyName.NEGATIVE3,
    PhotographyName.NEGATIVE4,
    PhotographyName.NEGATIVE5,
    PhotographyName.NEGATIVE6,
    PhotographyName.NEGATIVE7,
    PhotographyName.NEGATIVE8,
    PhotographyName.PLACEHOLDER,
    PhotographyName.POSITIVE1,
    PhotographyName.POSITIVE10,
    PhotographyName.POSITIVE11,
    PhotographyName.POSITIVE12,
    PhotographyName.POSITIVE13,
    PhotographyName.POSITIVE2,
    PhotographyName.POSITIVE3,
    PhotographyName.POSITIVE4,
    PhotographyName.POSITIVE5,
    PhotographyName.POSITIVE6,
    PhotographyName.POSITIVE7,
    PhotographyName.POSITIVE8,
    PhotographyName.POSITIVE9
  ],
  [CropType.PORTRAIT_MEDIUM]: [
    PhotographyName.BRANDMOMENT1,
    PhotographyName.BRANDMOMENT10,
    PhotographyName.BRANDMOMENT11,
    PhotographyName.BRANDMOMENT12,
    PhotographyName.BRANDMOMENT13,
    PhotographyName.BRANDMOMENT2,
    PhotographyName.BRANDMOMENT3,
    PhotographyName.BRANDMOMENT4,
    PhotographyName.BRANDMOMENT5,
    PhotographyName.BRANDMOMENT6,
    PhotographyName.BRANDMOMENT7,
    PhotographyName.BRANDMOMENT8,
    PhotographyName.BRANDMOMENT9,
    PhotographyName.CARDRENDER1,
    PhotographyName.CARDRENDER2,
    PhotographyName.CARDRENDER3,
    PhotographyName.GAMING1,
    PhotographyName.GENERAL1,
    PhotographyName.GENERAL10,
    PhotographyName.GENERAL11,
    PhotographyName.GENERAL12,
    PhotographyName.GENERAL13,
    PhotographyName.GENERAL14,
    PhotographyName.GENERAL15,
    PhotographyName.GENERAL16,
    PhotographyName.GENERAL17,
    PhotographyName.GENERAL18,
    PhotographyName.GENERAL19,
    PhotographyName.GENERAL2,
    PhotographyName.GENERAL20,
    PhotographyName.GENERAL21,
    PhotographyName.GENERAL22,
    PhotographyName.GENERAL23,
    PhotographyName.GENERAL24,
    PhotographyName.GENERAL25,
    PhotographyName.GENERAL26,
    PhotographyName.GENERAL27,
    PhotographyName.GENERAL3,
    PhotographyName.GENERAL4,
    PhotographyName.GENERAL5,
    PhotographyName.GENERAL6,
    PhotographyName.GENERAL7,
    PhotographyName.GENERAL8,
    PhotographyName.GENERAL9,
    PhotographyName.NEGATIVE1,
    PhotographyName.NEGATIVE2,
    PhotographyName.NEGATIVE3,
    PhotographyName.NEGATIVE4,
    PhotographyName.NEGATIVE5,
    PhotographyName.NEGATIVE6,
    PhotographyName.NEGATIVE7,
    PhotographyName.NEGATIVE8,
    PhotographyName.POSITIVE1,
    PhotographyName.POSITIVE10,
    PhotographyName.POSITIVE11,
    PhotographyName.POSITIVE12,
    PhotographyName.POSITIVE13,
    PhotographyName.POSITIVE2,
    PhotographyName.POSITIVE3,
    PhotographyName.POSITIVE4,
    PhotographyName.POSITIVE5,
    PhotographyName.POSITIVE6,
    PhotographyName.POSITIVE7,
    PhotographyName.POSITIVE8,
    PhotographyName.POSITIVE9
  ],
  [CropType.PORTRAIT_SMALL]: [
    PhotographyName.BRANDMOMENT10,
    PhotographyName.BRANDMOMENT9,
    PhotographyName.CARDRENDER1,
    PhotographyName.CARDRENDER2,
    PhotographyName.GENERAL1,
    PhotographyName.GENERAL10,
    PhotographyName.GENERAL12,
    PhotographyName.GENERAL22,
    PhotographyName.GENERAL3,
    PhotographyName.PLACEHOLDER,
    PhotographyName.POSITIVE4
  ],
  [CropType.LANDSCAPE_LARGE]: [
    PhotographyName.BRANDMOMENT1,
    PhotographyName.BRANDMOMENT13,
    PhotographyName.BRANDMOMENT3,
    PhotographyName.BRANDMOMENT5,
    PhotographyName.CARDRENDER1,
    PhotographyName.CARDRENDER2,
    PhotographyName.GENERAL1,
    PhotographyName.GENERAL2,
    PhotographyName.GENERAL6,
    PhotographyName.GENERAL8,
    PhotographyName.GENERAL9,
    PhotographyName.PLACEHOLDER,
    PhotographyName.POSITIVE1
  ],
} as const;


type PhotoCropAvailability = typeof photoCropAvailability;
/**
 * Convenience types for specific crops
 */
export type PhotosWithPortraitLargeCrop = PhotoCropAvailability[CropType.PORTRAIT_LARGE][number];
export type PhotosWithPortraitSmallCrop = PhotoCropAvailability[CropType.PORTRAIT_SMALL][number];
export type PhotosWithLandscapeLargeCrop = PhotoCropAvailability[CropType.LANDSCAPE_LARGE][number];


export const Photos: PhotographyMap = {
  [PhotographyName.BRANDMOMENT1]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/brandMoment1_portrait_large.webp'),
      [CropType.LANDSCAPE_LARGE]: require('@Assets/photography/generated/brandMoment1_landscape_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/brandMoment1_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.BRANDMOMENT10]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/brandMoment10_portrait_large.webp'),
      [CropType.PORTRAIT_SMALL]: require('@Assets/photography/generated/brandMoment10_portrait_small.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/brandMoment10_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.BRANDMOMENT11]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/brandMoment11_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/brandMoment11_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.BRANDMOMENT12]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/brandMoment12_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/brandMoment12_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.BRANDMOMENT13]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/brandMoment13_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/brandMoment13_portrait_medium.webp'),
      [CropType.LANDSCAPE_LARGE]: require('@Assets/photography/generated/brandMoment13_landscape_large.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.BRANDMOMENT2]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/brandMoment2_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/brandMoment2_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.BRANDMOMENT3]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/brandMoment3_portrait_large.webp'),
      [CropType.LANDSCAPE_LARGE]: require('@Assets/photography/generated/brandMoment3_landscape_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/brandMoment3_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.BRANDMOMENT4]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/brandMoment4_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/brandMoment4_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.BRANDMOMENT5]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/brandMoment5_portrait_large.webp'),
      [CropType.LANDSCAPE_LARGE]: require('@Assets/photography/generated/brandMoment5_landscape_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/brandMoment5_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.BRANDMOMENT6]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/brandMoment6_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/brandMoment6_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.BRANDMOMENT7]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/brandMoment7_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/brandMoment7_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.BRANDMOMENT8]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/brandMoment8_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/brandMoment8_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.BRANDMOMENT9]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/brandMoment9_portrait_large.webp'),
      [CropType.PORTRAIT_SMALL]: require('@Assets/photography/generated/brandMoment9_portrait_small.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/brandMoment9_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.CARDRENDER1]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/cardRender1_portrait_large.webp'),
      [CropType.PORTRAIT_SMALL]: require('@Assets/photography/generated/cardRender1_portrait_small.webp'),
      [CropType.LANDSCAPE_LARGE]: require('@Assets/photography/generated/cardRender1_landscape_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/cardRender1_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.CARDRENDER2]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/cardRender2_portrait_large.webp'),
      [CropType.PORTRAIT_SMALL]: require('@Assets/photography/generated/cardRender2_portrait_small.webp'),
      [CropType.LANDSCAPE_LARGE]: require('@Assets/photography/generated/cardRender2_landscape_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/cardRender2_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.CARDRENDER3]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/cardRender3_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/cardRender3_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.GAMING1]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/gaming1_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/gaming1_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.GENERAL1]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/general1_portrait_large.webp'),
      [CropType.LANDSCAPE_LARGE]: require('@Assets/photography/generated/general1_landscape_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/general1_portrait_medium.webp'),
      [CropType.PORTRAIT_SMALL]: require('@Assets/photography/generated/general1_portrait_small.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.GENERAL10]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/general10_portrait_large.webp'),
      [CropType.PORTRAIT_SMALL]: require('@Assets/photography/generated/general10_portrait_small.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/general10_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.GENERAL11]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/general11_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/general11_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.GENERAL12]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/general12_portrait_large.webp'),
      [CropType.PORTRAIT_SMALL]: require('@Assets/photography/generated/general12_portrait_small.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/general12_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.GENERAL13]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/general13_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/general13_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.GENERAL14]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/general14_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/general14_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.GENERAL15]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/general15_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/general15_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.GENERAL16]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/general16_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/general16_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.GENERAL17]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/general17_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/general17_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.GENERAL18]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/general18_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/general18_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.GENERAL19]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/general19_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/general19_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.GENERAL2]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/general2_portrait_large.webp'),
      [CropType.LANDSCAPE_LARGE]: require('@Assets/photography/generated/general2_landscape_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/general2_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.GENERAL20]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/general20_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/general20_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.GENERAL21]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/general21_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/general21_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.GENERAL22]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/general22_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/general22_portrait_medium.webp'),
      [CropType.PORTRAIT_SMALL]: require('@Assets/photography/generated/general22_portrait_small.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.GENERAL23]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/general23_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/general23_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.GENERAL24]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/general24_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/general24_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.GENERAL25]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/general25_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/general25_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.GENERAL26]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/general26_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/general26_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.GENERAL27]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/general27_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/general27_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.GENERAL3]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/general3_portrait_large.webp'),
      [CropType.PORTRAIT_SMALL]: require('@Assets/photography/generated/general3_portrait_small.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/general3_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.GENERAL4]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/general4_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/general4_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.GENERAL5]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/general5_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/general5_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.GENERAL6]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/general6_portrait_large.webp'),
      [CropType.LANDSCAPE_LARGE]: require('@Assets/photography/generated/general6_landscape_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/general6_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.GENERAL7]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/general7_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/general7_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.GENERAL8]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/general8_portrait_large.webp'),
      [CropType.LANDSCAPE_LARGE]: require('@Assets/photography/generated/general8_landscape_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/general8_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.GENERAL9]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/general9_portrait_large.webp'),
      [CropType.LANDSCAPE_LARGE]: require('@Assets/photography/generated/general9_landscape_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/general9_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.NEGATIVE1]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/negative1_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/negative1_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.NEGATIVE2]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/negative2_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/negative2_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.NEGATIVE3]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/negative3_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/negative3_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.NEGATIVE4]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/negative4_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/negative4_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.NEGATIVE5]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/negative5_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/negative5_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.NEGATIVE6]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/negative6_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/negative6_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.NEGATIVE7]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/negative7_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/negative7_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.NEGATIVE8]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/negative8_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/negative8_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.PLACEHOLDER]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/placeholder_portrait_large.webp'),
      [CropType.PORTRAIT_SMALL]: require('@Assets/photography/generated/placeholder_portrait_small.webp'),
      [CropType.LANDSCAPE_LARGE]: require('@Assets/photography/generated/placeholder_landscape_large.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.POSITIVE1]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/positive1_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/positive1_portrait_medium.webp'),
      [CropType.LANDSCAPE_LARGE]: require('@Assets/photography/generated/positive1_landscape_large.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.POSITIVE10]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/positive10_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/positive10_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.POSITIVE11]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/positive11_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/positive11_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.POSITIVE12]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/positive12_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/positive12_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.POSITIVE13]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/positive13_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/positive13_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.POSITIVE2]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/positive2_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/positive2_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.POSITIVE3]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/positive3_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/positive3_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.POSITIVE4]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/positive4_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/positive4_portrait_medium.webp'),
      [CropType.PORTRAIT_SMALL]: require('@Assets/photography/generated/positive4_portrait_small.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.POSITIVE5]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/positive5_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/positive5_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.POSITIVE6]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/positive6_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/positive6_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.POSITIVE7]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/positive7_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/positive7_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.POSITIVE8]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/positive8_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/positive8_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
  [PhotographyName.POSITIVE9]: {
    values: {
      [CropType.PORTRAIT_LARGE]: require('@Assets/photography/generated/positive9_portrait_large.webp'),
      [CropType.PORTRAIT_MEDIUM]: require('@Assets/photography/generated/positive9_portrait_medium.webp'),
    },
    appVersion: "2.7.0",
    isBackendDependant: false,
  },
};


