import fs from 'fs';
import path from 'path';
import { promisify } from 'util';

import { CropType, PhotographyConfig } from '../packages/photography/types/types';

// Promisify fs functions
const readdir = promisify(fs.readdir);
const writeFile = promisify(fs.writeFile);
const mkdir = promisify(fs.mkdir);
const access = promisify(fs.access);

// Paths configuration
const RAW_IMAGES_DIR = './packages/photography/assets/raw';
const CONFIG_DIR = './packages/photography/config';
const DEFAULT_CROP_TYPES = [CropType.PORTRAIT_LARGE];

function toCamelCase(filename: string): string {
  // Remove extension and split by common separators
  const parts = path.basename(filename, path.extname(filename)).split(/[-_\s]+/);

  // Convert to camelCase
  return parts
    .map((part, index) => {
      if (index === 0) {
        return part.toLowerCase();
      }
      return part.charAt(0).toUpperCase() + part.slice(1).toLowerCase();
    })
    .join('');
}

// Create config directory if it doesn't exist
async function ensureConfigDir(): Promise<void> {
  try {
    await access(CONFIG_DIR);
  } catch (error) {
    console.log(`Creating config directory: ${CONFIG_DIR}`);
    await mkdir(CONFIG_DIR, { recursive: true });
  }
}

async function createDefaultConfig(baseName: string): Promise<void> {
  const configPath = path.join(CONFIG_DIR, `${baseName}.ts`);

  try {
    await access(configPath);
    console.log(`Config already exists: ${configPath}`);
    return;
  } catch (error) {
    // File doesn't exist, create it
  }

  const defaultConfig: PhotographyConfig = {
    crops: DEFAULT_CROP_TYPES,
  };

  const defaultConfigContent = `import { CropType, PhotographyConfig } from '../types/types';

const config: PhotographyConfig = {
  crops: [${defaultConfig.crops.map((crop) => `CropType.${crop.toUpperCase()}`).join(', ')}],
};

export default config;
`;

  await writeFile(configPath, defaultConfigContent);
  console.log(`Created default config: ${configPath}`);
}

async function generateBarrelFile(): Promise<void> {
  const configFiles = await readdir(CONFIG_DIR);
  const tsFiles = configFiles.filter((file) => file.endsWith('.ts') && file !== 'index.ts');

  let content = '// Auto-generated barrel file for photography configs\n';
  content += '// DO NOT EDIT - This file is regenerated by the config generator script\n\n';

  tsFiles.forEach((file) => {
    const basename = path.basename(file, '.ts');
    content += `import ${basename}Config from './${basename}';\n`;
  });

  content += '\nexport const configs = {\n';
  tsFiles.forEach((file) => {
    const basename = path.basename(file, '.ts');
    content += `  ${basename}: ${basename}Config,\n`;
  });
  content += '};\n\n';

  content += 'export type ConfigKeys = keyof typeof configs;\n\n';
  content += 'export default configs;\n';

  const outputFile = path.join(CONFIG_DIR, 'index.ts');
  await writeFile(outputFile, content);
  console.log(`Generated barrel file: ${outputFile}`);
}

// Main function
async function generateConfigs(): Promise<void> {
  try {
    // Ensure config directory exists
    await ensureConfigDir();

    const files = await readdir(RAW_IMAGES_DIR);
    const imageFiles = files.filter((file) => {
      const ext = path.extname(file).toLowerCase();
      return ['.jpg', '.jpeg', '.png', '.webp', '.gif'].includes(ext);
    });

    console.log(`Found ${imageFiles.length} images to process for configs`);

    // Create default configs for each image if they don't exist
    for (const file of imageFiles) {
      const baseName = toCamelCase(file);
      await createDefaultConfig(baseName);
    }

    await generateBarrelFile();

    console.log('Config generation complete!');
  } catch (error) {
    console.error('Error generating configs:', error);
    process.exit(1);
  }
}

generateConfigs();
