import fs from 'fs';
import path from 'path';
import { promisify } from 'util';

// Promisify fs functions
const readdir = promisify(fs.readdir);
const writeFile = promisify(fs.writeFile);
const mkdir = promisify(fs.mkdir);
const access = promisify(fs.access);

// Paths configuration
const RAW_IMAGES_DIR = './packages/photography/assets/raw';
const CONFIG_DIR = './packages/photography/config';

function toCamelCase(filename: string): string {
  // Remove extension and split by common separators
  const parts = path.basename(filename, path.extname(filename)).split(/[-_\s]+/);

  // Convert to camelCase
  return parts
    .map((part, index) => {
      if (index === 0) {
        return part.toLowerCase();
      }
      return part.charAt(0).toUpperCase() + part.slice(1).toLowerCase();
    })
    .join('');
}

// Create config directory if it doesn't exist
async function ensureConfigDir(): Promise<void> {
  try {
    await access(CONFIG_DIR);
  } catch (error) {
    console.log(`Creating config directory: ${CONFIG_DIR}`);
    await mkdir(CONFIG_DIR, { recursive: true });
  }
}

async function generateBarrelFile(): Promise<void> {
  const configFiles = await readdir(CONFIG_DIR);
  const tsFiles = configFiles.filter((file) => file.endsWith('.ts') && file !== 'index.ts');

  let content = '// Auto-generated barrel file for photography configs\n';
  content += '// DO NOT EDIT - This file is regenerated by the config generator script\n\n';

  tsFiles.forEach((file) => {
    const basename = path.basename(file, '.ts');
    content += `import ${basename}Config from './${basename}';\n`;
  });

  content += '\nexport const configs = {\n';
  tsFiles.forEach((file) => {
    const basename = path.basename(file, '.ts');
    content += `  ${basename}: ${basename}Config,\n`;
  });
  content += '};\n\n';

  content += 'export type ConfigKeys = keyof typeof configs;\n\n';
  content += 'export default configs;\n';

  const outputFile = path.join(CONFIG_DIR, 'index.ts');
  await writeFile(outputFile, content);
  console.log(`Generated barrel file: ${outputFile}`);
}

// Main function
async function generateConfigs(): Promise<void> {
  try {
    // Ensure config directory exists
    await ensureConfigDir();

    const files = await readdir(RAW_IMAGES_DIR);
    const imageFiles = files.filter((file) => {
      const ext = path.extname(file).toLowerCase();
      return ['.jpg', '.jpeg', '.png', '.webp', '.gif'].includes(ext);
    });

    console.log(`Found ${imageFiles.length} images to process for configs`);

    await generateBarrelFile();

    console.log('Config generation complete!');
  } catch (error) {
    console.error('Error generating configs:', error);
    process.exit(1);
  }
}

generateConfigs();
